title: "Moinz.de Webservices"

theme: "jekyll-theme-cayman-blog"

header_pages:
 - "deploy.md"
 - "_fs/fs.md"
 - "msg.md"
 - "wobble.md"

collections:
 - fs:
    output: true



# social
github_username: zeisss