version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
    steps:
      - checkout
      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      - save_cache:
          paths:
            - /usr/local/bundle
            - /usr/local/lib/node_modules
          key: v2-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Jekyll build
          command: bundle exec jekyll build --verbose

      - run: mkdir -p workspace
      - run:
          name: "Build deploy tarball"
          command: tar -czvf workspace/site.tar.gz _site/

      - store_artifacts:
          path: "workspace/site.tar.gz"

      - persist_to_workspace:
          root: workspace
          paths:
            - "site.tar.gz"

  deploy:
    docker:
      - image: jimdo/debian-with-curl
    steps:
       - attach_workspace:
          # Must be absolute path or relative path from working_directory 
          at: /tmp/workspace
       - run:
          name: Upload build artifact
          command: |
            PROJECT=help.moinz.de
            curl -XPUT ${FS_ENDPOINT}/artifacts/${PROJECT}/${CIRCLE_BRANCH}-${CIRCLE_SHA1}/${PROJECT}.tar.gz \
              -d @/tmp/workspace/site.tar.gz -u ${FS_USER}:${FS_PASSWORD}


workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
            
