version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
    steps:
      - checkout
      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      - run:
          name: Jekyll build
          command: bundle exec jekyll build

      - store_artifacts:
          path: "_site"